# Learning Activity Bank {-}

The following activities are recommended for each unit. There are instructions in the course commentary, and your instructor may provide further direction.

## The Heart of a Teacher{-}

### Activity 1.1 {-}

**Reading and Reflective Learning Journal**

As we explore the importance of the “inner life of the teacher” as a
foundation for authentic learning, read Chapter 1: The Heart of a
Teacher: Identity and Integrity in Teaching in *The Courage to Teach*
(Palmer, 2017).

For this course, you will keep a Reflective Learning Journal, which will
provide the basis for many of your discussion posts. Writing can be a powerful
learning experience, as we engage in reflection and critical analysis of
the new concepts we discover. Through regular writing, we are challenged
to think critically, organize, and integrate these new concepts with our
prior understanding, as you prepare for your future teaching/coaching.

As you read, consider the following questions:

  - In your Reflective Learning Journal, write a summary sentence for
    each major idea/concept that relates to your understanding of what
    it means to be a teacher/facilitator/coach.

  - Choose the concept that most resonates with you and write a short
    paragraph summary of this concept, applied to your
    professional/personal context.

  - Formulate one question that emerged from this reading that you will
    explore and consider in future course readings and discussion posts.

  - As you prepare your discussion post, refer to these notes.

## Belonging to One’s Self{-}

### Activity 2.1: Who are you?{-}

For this activity, you are asked to share a little more about yourself with your peers. First, find a quote about either identity or integrity. For example, you may want to perform a Google image search for “identity quote.” Find one that resonates with you, and then include a picture of something that tells us something about you. Post the quote and your image to the Unit 2 Discussion forum with a 1-2 sentence explanation. This is a non-graded activity, but may help you reflect on this topic and to prepare for the assignment in this unit.


### Activity 2.2 {-}

View and Reflect View the following resources and reflect on your learning: - Read. Brown, B. (2017). Chapter 1: Everywhere and Nowhere. - Watch: Maya Angelou: <a href="http://billmoyers.com/content/conversation-maya-angelou/"><i>Interview with Bill Moyers</a> (7 minutes).

### Activity 2.3: Vulnerability Video{-}

:fa-film: Watch the TedTalk by Brene Brown: (20 minutes)

[LINK](https://www.youtube.com/watch?v=iCvmsMzlF7o) 


As you watch, consider the following questions:

1.  What elements of a learning community would create conditions for learners to be vulnerable about their fears about the course, their concerns about learning, and their questions regarding whether they are capable of achieving success in their course?

2.  In what ways do you feel vulnerable as a teacher/facilitator? Are there people with whom you can share this vulnerability?

:fa-pencil: You may want to answer these questions in your Reflective Learning Journal, and refer back to them as you complete the assessment for this unit.

### Activity 2.4: Reading{-}

Brown (2017) argues that authenticity is essential to belonging.

! "You will always belong anywhere you show up as yourself and talk about yourself and your work in a real way." ! -- Brene Brown (2017, p. 26)

### Activity 2.6: Listen and Reflect{-}

Listen to “[Brave](https://www.youtube.com/watch?v=QUQsqBqxoR4),” sung by Sara Bareilles.

As you listen to this song, consider the following questions:

1.  Is there an area in my current professional work where I need to be brave and speak up?

2.  What fears would keep me from sharing my thoughts or experience?

3.  How will I create a learning community that allows learners to share their thoughts authentically?


#### Activity 2.7: Self-Test{-}

Take the [Clance Imposter Phenomenon test](http://paulineroseclance.com/pdf/IPscoringtest.pdf). As you take the test, consider the areas in which you feel vulnerable in your work as a learner. How would you address these concerns for learners in courses you facilitate?


### Activity 2.8: {-}

Readings Read: Gardner, B., Avolio, B., Luthans, F., May, D. & Walumbwa, F. (2005) Can you see the real me? A self-based model of authentic leader and follower development. The Leadership Quarterly 16, pp. 343–372.

Optional Read: Cuddy, A. (2016). [I don’t deserve to be here: Presence and the imposter syndrome](https://leanin.org/news-inspiration/overcoming-imposter-syndrome-to-reveal-your-presence).


### Activity 2.9: Connection Activities  & Discussion{-}

“Liberating Structures” (Lipmanowicz & McCandless, 2013) are used in collaborative learning and work environments to create space for all participants to engage in collaborative inquiry and unleash innovation. One of these “Liberating Structures” is the strategy of the “Nine Whys,” which allows participants to clarify what is important in their work. You may choose to use a strategy like this in your role as a facilitator and teacher. For this learning activity, however, you will use the strategy of the “Nine Whys” to consider your own identity as a teacher/facilitator.

Identify someone in your life who knows you well, with whom you have a history of talking about your goals or dreams. Ask them to participate in this exercise with you.

1.  Begin by telling them why you are taking this course, as well as why you want to engage in teaching/coaching/facilitation.

2.  When you have finished talking, your “Nine Whys” partner will ask you: Why is that important to you?

3.  Your partner should continue asking that question up to nine times, or until you cannot go any deeper.

4.  At this point, you will have uncovered something fundamental about your identity as a teacher/facilitator.

As you complete this exercise, take detailed notes in your Reflective Learning Journal. You will be asked to create a discussion post about this experience in the Unit 2 Assessment.

