# The Role of Information and Perception in Choosing Strategies and an Appropriate Leadership Model

## Overview {-}

In this unit, you will learn about the role of information and perception in growth and development. This relates to learning communities in that communication among individuals related to information and growth in learning communities is so important. To put it another way, if information is miscommunicated or growth misrepresented, then the learning community is likely to experience challenges. You will explore the role of adult educator to be an advocate for adult learners. You will also explore the concept of the adult educator as servant leader and the importance of intentional practice based on this model of leadership. A servant leader has the interests of followers at heart therefore will make a greater effort to communicate effectively and assess growth of the community and individual in a fair manner.

## Topics {-}

- The Role of Information and Perception in Growth and Development

- The Adult Educator as Servant Leader

## Learning Outcomes {-}

When you have completed this unit you should be able to:

- Choose and/or design strategies with a critical lens for using information to influence growth and development of learners.
- Explain how an adult educator can be a servant leader.

## ✔️ Activity Checklist {-}

These learning activities will engage you in considering the guiding questions for this unit. As you plan your week, be sure to include time for these important learning activities. *Note that not all activities are required. Your instructor will provide guidance on key activities to complete.*

| **Activities**|
|----|
| Activity 7.1: Read assigned pages from Wheatley chapters 3, 5 and 7 and take notes in your journal.  |
| Activity 7.2: View Wheatley video [Islands of Sanity](https://youtu.be/LtaYNxp56gs).   |
| Activity 7.3: Browse Brookfield and Silberman for strategies related to critical thinking and jot down ideas in your journal.    |
| Activity 7.4: View the Ali Fett video [*Servant Leadership - How a jar can change the way you lead and serve*](https://youtu.be/1vIPrR_clEg).   |
| Activity 7.5: Respond in your discussion post for this unit.   |

## The Role of Information and Perception in Growth and Development

> "Information is the source of all growth and development in a living system" (Wheatley, 2017, p. 101).

Wheatley goes on to explain how information has changed from

> "communications among people to high speed transmissions delivered in cyberspace" (p. 104).

While information is still important, it is the mode of delivery that has reshaped culture. She argues that the digital age has destroyed the information age. The adult educator can respond to her call to re-establish our relationships with the real world by choosing strategies that privilege connection and meaning and lead to better decisions. She illustrates this by describing in some depth the value of an 'After Action Review' (see pages 128-132). Consider how this might be adapted for the adult education setting in your context.

Perception based on scientific understanding is not the only way of knowing. Wheatley admonishes:

> "There are other ways of knowing reality, reliable methods that have served humans and earlier hominids for millennia. It is the arrogance of our science that denies their existence and their usefulness" (p. 179).

How can adult educators incorporate other ways of knowing? Cahalan, K. (2016) has identified eight ways of knowing that are essential to wise practice:

- Situated awareness is noticing and describing contextual factors.
- Embodied realizing is developing skilled competence in bodily action.
- Conceptual understanding is comprehending and remembering key information.
- Critical thinking is analyzing and evaluating concepts and actions.
- Emotional attunement is identifying and using awareness of feelings and affective states.
- Creative insight is developing imaginative and creative responses.
- Spiritual discernment is perceiving what is of God and not of God.
- Practical reasoning is problem-solving, forming judgments, gaining a sense of salience, and acting wisely.

How we perceive, and teach learners to perceive, matters greatly and is a foundational responsibility of the adult educator. For example, in choosing texts, articles or other resources the type of information you get students to pay attention to will affect their awareness of contextual factors. Embodied realizing in the classroom may take the form of an experiential learning activity where the students are asked to interview someone, ‘shadow’ them for a time or else listen to a podcast and describe their ‘gut reactions’ or impressions. Reading biographies is an excellent way for learners to become more emotionally attuned to the feelings and affective states of others. This develops empathy – a crucial component of being hospitable in a diverse, pluralistic society.

Wheatley identifies a warrior for the human spirit as

> "a decent human being who aspires to be of service in an indecent, inhumane time" (p. 255).

In this sense, adult educators are called to be warriors for the human spirit. Read pages 258-259 for ethical principles that are quite likely to move you and profoundly influence your perception of your role.

### Learning Activity

```{block, type='reflect'}
Read Wheatley, M. (2017). *Who Do We Choose to Be? : Facing Reality, Claiming Leadership, Restoring Sanity.* Oakland, CA: Berrett-Koehler Publishers. Wheatley chapters 3 (pages 100-139),  5 (pages 172-209 ) and 7 (pages 252-270).

As you read answer the following questions in your Reflective Learning Journal:

- How are adult educators ‘warriors for the human spirit’?
- How does this relate specifically to your present or future context?
```

### Learning Activity

```{block, type='reflect'}
View Margaret Wheatley's *Islands of Sanity* (42 minutes).

https://youtu.be/LtaYNxp56gs


After viewing the video and reading chapters 3, 5 and 7 of Wheatley, consider the following:

- What is the meaning of your work as a coach/facilitator?
- How and why do you persevere?
```


### Learning Activity

```{block, type='reflect'}
Browse the following two resources and choose strategies that could be used to encourage critical thinking about information. Think about how you might adapt these strategies for your context. Jot down your ideas in your reflective journal.

- Brookfield, Stephen and Preskill, S. (2016). *The discussion book: 50 great ways to get people talking*. San Francisco: Jossey Bass.  
- Silberman, M. L., & Biech, E. (2015). *Active training: A handbook of techniques, designs, case examples, and tips* (4th ed.). Wiley.
```
