# Assessment {-}

The following assignments are opportunities for learners to demonstrate their understanding of the course outcomes.  Please confirm assignment details with your instructor, referring to the course syllabus.

Note that Assignment dropboxes are located in Moodle.  Also refer to the Course Schedule in Moodle for the specific due dates.

## Community of Inquiry (Discussions) {-}

```{block2, type='assessment'}

In this course, we ask you to discuss ideas with your colleagues, challenging one another and analyzing key course resources. At the end of each units you are asked to address questions in a Moodle Forum and respond to your peers. These discussions are worth 30% of your course grade.


```

<details>
<summary class="carbottom">**Discussion Rubric** *- The Discussion Rubric may be used to measure your engagement and understanding of the course learning outcomes. (Click to expand).*</summary>

- [PDF Version](assets/assessment/LDRS664_DiscussionRubric.pdf){target="_blank"}

| Mark                             | Details                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|----------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **9-10**<br/>*Exemplary*         | • Identifies information from the assigned reading and viewing that resonates or is striking and clearly explains the reason for their choices.<br/>• The responses show superior depth of knowledge on the topic, clear synthesis and analysis of the content, and provide depth, breath, or new insight to the topic.<br/>• Demonstrates an accurate understanding of this chosen information.<br/>• Uses information from the text to interpret chosen concepts or make connections to other situations or contexts logically through analysis, evaluation, inference, or comparison/contrast.<br/>• Defines uncommon or challenging words and shows evidence of doing the intellectual work necessary to understand challenging text.<br/>• Identifies points of view and implications in the text and critically analyses own response to these.<br/>• No errors in grammar or composition. Word limit and format followed. Posted on time.                                                                 |
| <br/>**6-8**<br/>*Proficient*   | • Identifies information from the assigned reading and viewing that resonates or is striking but the reason for their choices is not completely or clearly explained.<br/>• The responses show adequate depth of knowledge on the topic, a good synthesis but may lack in evaluation of the content read, and providing new insight to the topic.<br/>• Demonstrates a partial understanding of this chosen information in the text or viewing.<br/>• Uses information from the text/viewing to interpret chosen concepts but does not make<br/>connections to other situations or contexts.<br/>• Partially integrates interpretation of the text with text-based support.<br/>• Does not define uncommon or challenging words necessary to understanding the text.<br/>• Does not identify points of view and implications in the text or critically analyze their own<br/>response to these.<br/>• Fewer than 3 errors in grammar or composition. Word limit and format not followed. Not<br/>posted on time. |
| <br/>**3-5**<br/>*Developing*   | • Demonstrates insufficient understanding of the chosen concepts.<br/>• Responses show inadequate depth of knowledge on the topic, a synthesis that misses key concepts, and is not a critical analysis.<br/>• Uses information from the text to make simplistic interpretations of the text without using significant concepts or by making only limited connections to other situations or contexts.<br/>• Does not integrate interpretation of the text with text-based support.<br/>• Does not define uncommon or challenging words necessary to understanding the text.<br/>• Does not identify points of view and implications in the text or critically analyze their own response to these.<br/>• More than 3 errors in grammar or composition. Word limit and format followed. Not posted<br/>on time.                                                                                                                                                                                                  |
| <br/>**1-2**<br/>Unsatisfactory | • Demonstrates little or no understanding of the text; may be inaccurate. Responses are superficial and do not include critical analysis.<br/>• Little or no interpretation of the text.<br/>• Response is insufficient to show that criteria are met.<br/>• More than 5 errors in grammar or composition. Word limit and format followed. Not posted on time.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| <br/>**0**<br/>*Incomplete*     | • Response is absent or does not address the task.<br/>• Response is insufficient to show that criteria are met.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |

</details>


## Assignment: Identity as a Teacher/Facilitator {-}

```{block2, type='assessment'}

Building on your learning in the first three units in this course, write a 3-4 page paper in which you describe your identity as a teacher/facilitator. Incorporate references to the unit resources, as well as other resources from your graduate coursework. The paper should include an introduction, a statement of your identity as a teacher/facilitator, and a discussion of three important aspects of that identity. Your conclusion should include a discussion of how you will use your identity to create authentic spaces for learning in the courses you facilitate/teach.

```

<details><summary class="carbottom">**Grading Rubric** *- The rubric explains how your assignment will be evaluated (Click to expand).*</summary>  

- [PDF Version](assets/assessment/Identity-as-a-Teacher-RUBRIC.pdf)

|                                                    | Unsatisfactory                                                                                                                                                                                                             | Developing                                                                                                                                                                                                                                                        | Proficient                                                                                                                                                                                                                                                                                                     | Exemplary                                                                                                                                                                                                                                           |
|-----------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **APA/Writing**                                         | Paper does not model language and conventions used in scholarly literature. Writing is not well-organized. Several errors in grammar or composition. Sources are not cited. APA citations are not appropriately formatted. | Paper partially models language and conventions used in scholarly literature. Writing is somewhat well organized and includes some errors in grammar or composition. Not all sources cited. APA citations are generally formatted correctly, with several errors. | Paper consistently models language and conventions used in scholarly literature. Writing is well-organized and includes few (if any) errors in grammar or composition. All resources are appropriately cited (including in-text citations and bibliography information). Few (if any) errors in APA citations. | Paper is an exemplar of language and conventions used in scholarly literature. Writing is well-organized and free of errors in grammar or composition. All resources are appropriately cited. No errors in APA format.                              |
| **Statement of Teaching Identity**                      | Does not provide a statement about identity as a teacher/facilitator                                                                                                                                                       | Provides an unclear statement about identity as a teacher/facilitator.                                                                                                                                                                                            | Provides a clear, concise, and powerful statement about identity as a teacher/facilitator.                                                                                                                                                                                                                     | Provides a clear, concise, and powerful statement about identity as a teacher/facilitator. Statement incorporates theory or research from course materials.                                                                                         |
| **Developing a Cohesive and Logical Academic Argument** | Does not make a focused, cohesive, or logical academic argument. Paper is confusing, and is missing an introduction, body, or conclusion. Transitions between sections and ideas are missing.                              | Makes an academic argument that is only partially focused, cohesive and logical. Paper is generally organized, but is missing an introduction, body, or conclusion. Transitions between sections and ideas are unclear.                                           | Makes a focused, cohesive, logical academic argument. Paper is effectively organized and includes an introduction, body, and conclusion. Transitions between sections and ideas are clear.                                                                                                                     | Makes a focused, cohesive, logical and compelling academic argument. Paper is effectively organized and includes an introduction, body, and conclusion. Transitions between sections and ideas are clear, and build on each other.                  |
| **Analysis of Identity as a Teacher**                   | Does not include three important aspects of identity as a teacher/facilitator. Does not include an analysis.                                                                                                               | Lists but does not discuss three important aspects of identity as a teacher/facilitator. Includes a partial analysis.                                                                                                                                             | Includes a detailed discussion of three important aspects of identity as a teacher/facilitator. Includes thoughtful analysis of each of the three elements.                                                                                                                                                    | Includes a detailed discussion of three important aspects of identity as a teacher/facilitator. Includes a thoughtful analysis, integrating scholarly literature to support analysis and furthering scholarly thinking related to teacher identity. |
| **Scholarly Integration**                               | Does not integrate references to support claims and assertions made in the paper.                                                                                                                                          | Integrates references to support some of the claims and assertions made in the paper.                                                                                                                                                                             | Integrates references to support claims and assertions made in the paper.                                                                                                                                                                                                                                      | Integrates references to support claims and assertions made in the paper, effectively synthesizing different perspectives and research results from scholarly sources.                                                                              |
| **Total** | 0 = 0% (F) | 10 = 50% (C) | 15 = 75 (B) | 20 = 100% (A+) |

</details>

## Assignment: Company Website Analysis {-}

```{block2, type='assessment'}
Investigate the Human Resources or Faculty Development portion of a company's website, a higher education institution or adult learning facility, preferably one with which you are familiar. Focus on the faculty or employee development part of the website. In this assignment, you will apply the theory of teaching in/for/with depth by analyzing the learning culture of an organization.

**In a 4-5 page APA formatted paper, analyze the website by responding to the following questions in your report:**

1. What can you infer about the company’s learning culture?  
2. From what is visible on the public website, would you say it is an authentic learning community? Why or why not? Discuss whether the website reflects aspects of one or more of the learning community models explored in previous lessons.  
3. Do you see evidence that interconnectedness and integrity are valued?  Explain.  
4. What traits and skills seem to be valued in employees?  
5. How does the company develop skills in its employees (e.g., workshops, seminars, mentoring)? Are the methods based on the principles of andragogy? (see Smith YouTube video). What specific adult learning strategies do you see reflected in the development/training opportunities for employees?  

Your paper should be 4-5 pages and should incorporate references to at least five scholarly sources you have studied in this course, or other scholarly sources you have identified.

**The paper should include:**

1. Introduction  
2. Analysis (responding to the prompts)  
3. Conclusion  
4. Reference List  

```

<details>
<summary class="carbottom">**Company Website Analysis Rubric** *- See the following rubric that explains how your assignment will be evaluated. (Click to expand).*</summary>

- [PDF Version](assets/assessment/Company-Website-Analysis-RUBRIC.pdf){target="_blank"}

|        | Unsatisfactory | Developing | Proficient | Exemplary |
|--------|----------------|------------|------------|-----------|
| **APA Formatting** | Paper does not model language and conventions used in scholarly literature. Writing is not well-organized. Several errors in grammar or composition. Sources are not cited. APA citations are not appropriately formatted. | Paper partially models language and conventions used in scholarly literature. Writing is somewhat well organized and includes some errors in grammar or composition. Not all sources cited. APA citations are generally formatted correctly, with several errors. | Paper consistently models language and conventions used in scholarly literature. Writing is well-organized and includes few (if any) errors in grammar or composition. All resources are appropriately cited (including in-text citations and bibliography information). Few (if any) errors in APA citations. | Paper is an exemplar of language and conventions used in scholarly literature. Writing is well-organized and free of errors in grammar or composition. All resources are appropriately cited. No errors in APA format.                                                                   |
| **Developing a Cohesive and Logical Academic Argument** | Does not make a focused, cohesive, or logical academic argument. Paper is confusing, and is missing an introduction, body, or conclusion. Transitions between sections and ideas are missing.                              | Makes an academic argument that is only partially focused, cohesive and logical. Paper is generally organized, but is missing an introduction, body, or conclusion. Transitions between sections and ideas are unclear.                                           | Makes a focused, cohesive, logical academic argument. Paper is effectively organized and includes an introduction, body, and conclusion. Transitions between sections and ideas are clear.                                                                                                                     | Makes a focused, cohesive, logical and compelling academic argument. Paper is effectively organized and includes an introduction, body, and conclusion. Transitions between sections and ideas are clear and build on each other.                                                        |
| **Analysis of Learning Culture**  | Does not include an analysis of the company learning culture, and no evaluation of the authenticity of the learning community.                                                                                             | Includes a partial analysis of the company learning culture, including a limited evaluation of the authenticity of the learning community.                                                                                                                        | Includes a detailed analysis of the company learning culture, including an evaluation of the authenticity of the learning community.                                                                                                                                                                           | Includes a detailed analysis of the company learning culture, including an evaluation of the authenticity of the learning community. Includes a thoughtful analysis, integrating scholarly literature to support analysis and furthering scholarly thinking related to teacher identity. |
| **Evaluation of Interconnectedness and Integrity** | Does not include an evaluation of evidence of interconnectedness and integrity on the company website. Does not integrate scholarly sources in the evaluation.                                                             | Includes a partial evaluation of evidence of interconnectedness and integrity on the company website. Evaluation includes only limited reference to scholarly sources.                                                                                            | Includes a detailed evaluation of evidence of interconnectedness and integrity on the company website. Evaluation integrates scholarly sources.                                                                                                                                                                | Includes a detailed evaluation of evidence of interconnectedness and integrity on the company website. Includes recommendations for ways in which to integrate interconnectedness and integrity into employee development.                                                               |
| **Analysis of Adult Learning Strategies** | Does not include a detailed analysis of valued skills and evidence of adult learning theory in employee development. Does not integrate scholarly sources.                                                                 | Includes a partial analysis of valued skills and evidence of adult learning theory in employee development. Analysis integrates few, if any, scholarly sources.                                                                                                   | Includes a detailed analysis of valued skills and evidence of adult learning theory in employee development. Analysis integrates scholarly sources.                                                                                                                                                            | Includes a detailed analysis of valued skills and evidence of adult learning theory in employee development. Includes recommendations for ways in which to integrate adult learning theory into employee development.                                                                    |
| **Scholarly Integration** | Does not integrate scholarly references to support claims and assertions made in the paper.                                                                                                                                | Integrates scholarly references to support some of the claims and assertions made in the paper.                                                                                                                                                                   | Integrates scholarly references to support claims and assertions made in the paper.                                                                                                                                                                                                                            | Integrates scholarly references to support claims and assertions made in the paper, effectively synthesizing different perspectives and research results from scholarly sources.                                                                                                         |
| **Total** | 0 = 0% (F) | 10 = 50% (C) | 15 = 75 (B) | 20 = 100% (A+) |

</details>

## Assignment: Platform Paper {-}

```{block2, type='assessment'}

For this assignment, you will write a contextualized Platform Paper in which you discuss your ideal learning community and your role as teacher/leader of that learning community. Select a context for your paper (i.e. facilitating in a FAR Centre in a specific country, teaching adult learners, facilitating employee development workshops, etc.).
Your paper should be written and referenced in APA format and include references to a minimum of 10 scholarly sources (this can include literature you read in this course).
You will write a draft of the Platform Paper in Unit 8 and post for Peer Review. In Unit 9, you will provide feedback to another learner on their paper. You will make revisions based on the Peer Review and, in Unit 10, you will submit the final Platform Paper. Peer reviewers will be assigned in advance.

<span class="blockhead">Paper Outline</span>

**This paper will be 12-15 pages long, and should include:**

1. Introduction (1-2 pages)  
2. Section 1: Ideal Learning Environment (5-7 pages)  
3. Section 2: Your Role as Teacher and Leader (5-7 pages)  
4. Conclusion (1-2 pages)  

<span class="blockhead">Paper Guidelines</span>

- **Introduction**: Introduce the two sections in your paper, providing a brief description of the key points you will make in each section.  
- **Section 1**: In section one, you will describe your ideal education learning environment. This section should demonstrate your learning about authentic learning communities, incorporating scholarly sources and your own analysis to depict your ideal learning environment. Incorporate a discussion of the learning community environment, learning experiences, student learning outcomes, and personal beliefs about teaching and learning.  
- **Section 2**: In this section, describe your role as a teacher or leader within an authentic learning community. Incorporating scholarly literature, analyze your role as a facilitator/leader in planning learning experiences, facilitating student learning, and assessing student learning. Describe the actions, practices, and strategies you will engage in to achieve your vision of the learning community you described in section one.  
- **Conclusion**: Summarize the key points you made in each section.  
- **References**: Include a reference list with references to at least 10 scholarly sources.  

```

<details>
<summary class="carbottom">**Platform Paper Rubric** *- See the following rubric that explains how your assignment will be evaluated. (Click to expand).*</summary>

- [PDF Version](assets/assessment/Platform-Paper-RUBRIC.pdf){target="_blank"}

|                                                        | Unsatisfactory                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Developing                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Proficient                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | Exemplary                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|---------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **APA/Writing**                                         | Paper does not model language and conventions used in scholarly literature. Writing is not well-organized. Several errors in grammar or composition. Sources are not cited. APA citations are not appropriately formatted.                                                                                                                                                                                                                                                                   | Paper partially models language and conventions used in scholarly literature. Writing is somewhat well organized and includes some errors in grammar or composition. Not all sources cited. APA citations are generally formatted correctly, with several errors.                                                                                                                                                                                                                     | Paper consistently models language and conventions used in scholarly literature. Writing is well-organized and includes few (if any) errors in grammar or composition. All resources are appropriately cited (including in-text citations and bibliography information). Few (if any) errors in APA citations.                                                                                                                                                                                 | Paper is an exemplar of language and conventions used in scholarly literature. Writing is well-organized and free of errors in grammar or composition. All resources are appropriately cited. No errors in APA format.                                                                                                                                                                                                                                                                                                                                           |
| **Developing a Cohesive and Logical Academic Argument** | Does not make a focused, cohesive, or logical academic argument. Paper is confusing, and is missing an introduction, body, or conclusion. Transitions between sections and ideas are missing.                                                                                                                                                                                                                                                                                                | Makes an academic argument that is only partially focused, cohesive and logical. Paper is generally organized, but is missing an introduction, body, or conclusion. Transitions between sections and ideas are unclear.                                                                                                                                                                                                                                                               | Makes a focused, cohesive, logical academic argument. Paper is effectively organized and includes an introduction, body, and conclusion. Transitions between sections and ideas are clear.                                                                                                                                                                                                                                                                                                     | Makes a focused, cohesive, logical and compelling academic argument. Paper is effectively organized and includes an introduction, body, and conclusion. Transitions between sections and ideas are clear and build on each other.                                                                                                                                                                                                                                                                                                                                |
| **Ideal Learning Environment**                          | Does not include a description of your ideal learning environment. Does not reference scholarly sources. Does note analyze key elements of an authentic learning community. Does not mention or describe the learning community environment, student learning outcomes, learning outcomes and personal beliefs about teaching and learning.                                                                                                                                                  | Includes a partial description of your ideal learning environment, referencing few scholarly sources and including a partial analysis of key elements of an authentic learning community. Mentions some elements, but does not fully describe the learning community environment, student learning outcomes, learning outcomes and personal beliefs about teaching and learning.                                                                                                      | Includes a detailed description of your ideal learning environment, referencing scholarly sources and analyzing key elements of an authentic learning community. Describes the learning community environment, student learning outcomes, learning outcomes and personal beliefs about teaching and learning.                                                                                                                                                                                  | Includes a detailed description of your ideal learning environment, referencing scholarly sources and analyzing key elements of authentic learning communities. Provides a rationale for key elements of the learning community environment, student learning outcomes, learning outcomes and personal beliefs about teaching and learning. Advances scholarly thinking about authentic learning communities.                                                                                                                                                    |
| **Your Role as Teacher and Leader**                     | Does not include a description of your role as a teacher or leader within an authentic learning community, incorporating scholarly literature. Does not include an analysis of your role as a facilitator/leader in planning learning experiences, facilitating student learning, and assessing student learning. Does not include a description of the actions, practices, and strategies you will engage in to achieve your vision of the learning community you described in section one. | Includes a partial description of your role as a teacher or leader within an authentic learning community, incorporating scholarly literature. Describes but does not analyze your role as a facilitator/leader in planning learning experiences, facilitating student learning, and assessing student learning. Lists but does not describe the actions, practices, and strategies you will engage in to achieve your vision of the learning community you described in section one. | Includes a detailed description of your role as a teacher or leader within an authentic learning community, incorporating scholarly literature. Includes a detailed analysis of your role as a facilitator/leader in planning learning experiences, facilitating student learning, and assessing student learning. Includes a detailed description of the actions, practices, and strategies you will engage in to achieve your vision of the learning community you described in section one. | Includes a detailed analysis of your role as a teacher or leader within an authentic learning community, incorporating scholarly literature. Includes a detailed analysis of your role as a facilitator/leader in planning learning experiences, facilitating student learning, and assessing student learning. Includes a detailed description of the actions, practices, and strategies you will engage in to achieve your vision of the learning community you described in section one. Synthesizes scholarly thinking about the role of the teacher/leader. |
| **Scholarly Integration**                               | Does not integrate scholarly references to support claims and assertions made in the paper.                                                                                                                                                                                                                                                                                                                                                                                                  | ntegrates fewer than 10 scholarly sources to support arguments made in the paper.                                                                                                                                                                                                                                                                                                                                                                                                     | Integrates a minimum of 10 scholarly sources to support arguments made in each section of the paper.                                                                                                                                                                                                                                                                                                                                                                                           | Integrates a minimum of 10 references to support the arguments made in each section, including several scholarly sources not included in course materials.                                                                                                                                                                                                                                                                                                                                                                                                       |
| **Total** | 0 = 0% (F) | 10 = 50% (C) | 15 = 75 (B) | 20 = 100% (A+) |

</details>


