# Course Credits {-}

## Course Contributors
### Curriculum Developer
***Catharine (Cathy) Penfold Navarro, Ph.D.***
Catharine Penfold Navarro, Ph.D., is a higher education leader and scholar with a focus on leadership, faculty and staff development, learning-centered teaching strategies, learning assessment, creating inclusive learning communities, and academic advising. Dr. Penfold Navarro is passionately committed to authentic learning and to creating inclusive learning experiences for students that result in meaningful connections with the discipline, faculty, and student colleagues.

Dr. Penfold Navarro served as the Vice Provost, Teaching + Learning at Trinity Western University from 2016-2018. Prior to her work at TWU, Dr. Penfold Navarro served as Project Director for a $1.89 million grant from the US Department of Education at Valencia College in Orlando, Florida. There she led faculty and staff in action research focused on the infusion of college success skills across the curriculum, and integrating learning-centered strategies into academic advising. At Valencia College, she also led the faculty of Student Success and provided administrative leadership for Learning in Community (LinC), Service Learning, and Supplemental Learning, designed to close the gaps in student achievement and facilitate student success.

Dr. Penfold Navarro has previously provided leadership for academic advising, faculty development, and student development initiatives at the University of Kentucky, Bluegrass Community and Technical College, Asbury College, and LCC International University in Lithuania.


### Course Instructors
- Cathy Penfold Navarro
- Daniel To
- Marilyn Ang


## Copyright & Credits
Copyright © 2023 Trinity Western University. All rights reserved.

The content of this course material is the property of Trinity Western University (TWU) and is protected by copyright law worldwide. This material may be used by students enrolled at TWU for personal study purposes only.

TWU seeks to ensure that any course content that is owned by others has been appropriately cleared for use in this course. Anyone wishing to make additional use of such third party material must obtain clearance from the copyright holder.
Course Development Team

Course Writer: Catharine Penfold Navarro, Ph.D.
Instructional Designer: Kelly Marjanovic, M.A., Cert. Learning Technologies
Production Team: Colin Madland, Manager of Online Learning and Instructional Technology;
Academic Director: Phil Laird, Ph.D., Vice President of Innovation, Global and Academic Partnerships

Trinity Western University
22500 University Drive
Langley, BC, Canada | V2Y 1Y1

