# References {-}

The following are key references used in this course.  ***Check with your course syllabus for required readings.***

Atha, D.L., Castellon, A.R., Strong, H., & Wu, T. (2017). MA Leadership and MA in Educational Leadership Monograph 2018. Unpublished Manuscript Trinity Western University, Langley BC, (70), 22–32.

Athabasca University. (n.d.) Community of Inquiry Model. Retrieved from: https://coi.athabascau.ca/coi-model

Arntz, V. 2018. Flannery O’Connor & Redemption Amidst the Grotesque. Available at https://catholicexchange.com/flannery-oconnor-redemption-amidst-grotesque.

Bell, T., Urhahne, D., Schanze, S., & Ploetzner, R. (2009). Collaborative inquiry learning: models, tools, and challenges. International Journal of Science Education. (32)3, 349-377.

Brookfield, S. and Preskill, S. (2016). The Discussion Book: 50 Great Ways to Get People Talking. San Francisco: Jossey Bass.  Various; as needed

Brookfield, S. (2013).  Powerful Techniques for Teaching Adults. San Francisco: Jossey-Bass.

Brower, A., Carlson-Dakes, C.G., Barger, S.S. (2007). A learning community model of graduate student professional teaching excellence. Wisconsin Center for the Advancement of Postsecondary Education. Retrieved from: https://www.wiscape.wisc.edu/docs/wiscapedocuments/wp003.pdf?sfvrsn=8

Brower, A. & Dettinger, K. (1998). What is a learning community?: Toward a comprehensive model. About Campus: Enriching the Student Experience. 3(5), 15-21.

Brown, B. (2017). Braving the wilderness: The quest for true belonging and the courage to stand alone. New York: Penguin Random House.

Burwell, R. & Huyser, M. (2013). Practicing hospitality in the classroom. International Journal of Christianity and Education. 17(1), 9-24

Cahalan, K. (2016). Integrative knowing and practica wisdom in Reflective practice: Formation and supervision in ministry.

Castellon, A. (2017). Indigenous Integration: 100+ Lesson Ideas for Secondary and College Teachers. Vic: Tellwell.

Donohoo, J. & Velasco, M. (2016). The Transformative Power of Collaborative Inquiry. Corwin (SAGE): Thousand Oaks, CA.

Escobar, B.  Sense of Belonging

Gardner, W.L., Avolio, B.J., Luthans, F., May, D.R., & Walumbwa, F. (2005). “Can you see the real me?” A self-based model of authentic leader and follower development. The Leadership Quarterly, (16), pp. 343-372.

Greenleaf, R. 1998. The power of servant-leadership. San Francisco, CA: Berrett-Koehler.

Hewlett, S. (2014). Executive Presence. New York: HarperCollins.

Ibarra, H. (2015).  Act Like a Leader, Think like a Leader.  Boston, MA. Harvard Business Review Press.

Lipmanowicz, H. & McCandless, K. (2013). The surprising power of liberating structures: Simple rules to unleash a culture of innovation. Liberating Structures Press.   

Lytkina Botelho, E. Rosenkoetter Powell, K, Kincaid, S. and Wang D. (May-June 2017).  What Sets Successful CEOs Apart. Harvard Business Review.

Madland, C. (2017). The Trinity Community of Inquiry. Creative Commons License.

Palmer, P. (2017). The courage to teach: Exploring the inner landscape of a teacher’s life. San Francisco: Wiley.

Parris, D.L. & Welty Peachey, J. (20130. A Systematic Literature Review of Servant Leadership Theory in Organizational Contexts. J. of Bus. Ethics 113: 377-393.

Rachels, J. (1986). The Elements of Moral Philosophy, pp. 114-17,122-23. NY: Random House, Inc.

Rilke, R.M. Ah, Not to be Cut Off  

Schuyler, K. (2014).   Leading with Spirit, Presence, & Authenticity.  San Francisco: Jossey-Bass.

Silberman, M. L., & Biech, E. (2015). Active training: A handbook of techniques, designs, case examples, and tips (4th ed.). Wiley. Various; as needed.

Taylor Swift: A Place in this World

Wheatley, M. (2017). Who Do We Choose to Be? : Facing Reality, Claiming Leadership, Restoring Sanity. Oakland, CA: Berrett-Koehler Publishers.

Whitney, D., Trosten-Bloom, Amanda. The Power of Appreciative Inquiry: A Practical Guide to Positive Change,  2nd Edition. Berrett-Koehler Publishers, 03/2010.
